spring:
  application:
    name: simple-noteApp # 프로젝트의 이름
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 👇 여기부터 수정! spring과 같은 라인(맨 앞)으로 빼주세요.
jwt:
  secret: V2hhdEFEZWFkYmVlZlNlY3JldEtleVN0cmluZzEyMzQ1Njc4OTA=
  expiration_time: 3600000